global:
  # Seberapa sering Prometheus mengambil metrik (scrape)
  scrape_interval: 5s 
  evaluation_interval: 5s 

scrape_configs:
  # Konfigurasi untuk aplikasi Flask API kita
  - job_name: 'credit_scoring_api'
    # Default path untuk metrik dari prometheus_flask_exporter adalah /metrics
    metrics_path: '/metrics'
    static_configs:
      # Targets: Alamat di mana Prometheus akan mencari metrik.
      # Karena kita menjalankannya secara lokal, alamatnya adalah localhost:5000.
      - targets: ['localhost:5000']