name: CI/CD - MLOps Model Training

on:
  push:
    branches:
      - main
    paths:
      # Pemicu workflow jika file-file berikut berubah
      - 'modelling_tuning.py'
      - 'Dockerfile'
      - 'requirements.txt'
      - 'namadataset_preprocessing/**'

jobs:
  train_model_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Langkah debug yang berguna
      - name: Debug - List files in repo
        run: ls -R .

      - name: Build Docker Image
        run: docker build -t credit-scoring-model .

      - name: Debug - Check Docker image exist
        run: docker images

      - name: Run Model Training in Docker
        run: |
          # --- KONFIGURASI MLFLOW TERBARU ---
          docker run \
            --env DAGSHUB_USERNAME=${{ secrets.DAGSHUB_USERNAME }} \
            --env DAGSHUB_TOKEN=${{ secrets.DAGSHUB_TOKEN }} \
            --env MLFLOW_TRACKING_URI="https://dagshub.com/${{ secrets.DAGSHUB_USERNAME }}/mlops-credit-scoring-margohan/mlflow" \
            --env MLFLOW_TRACKING_USERNAME=${{ secrets.DAGSHUB_USERNAME }} \
            --env MLFLOW_TRACKING_PASSWORD=${{ secrets.DAGSHUB_TOKEN }} \
            credit-scoring-model

        env:
          DAGSHUB_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
          DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
